/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AudibleRouteImport } from './routes/audible'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as SpatialReaderRouteImport } from './routes/spatial-reader'
import { Route as VirtualLibraryRouteImport } from './routes/virtual-library'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AudibleRoute = AudibleRouteImport.update({
  id: '/audible',
  path: '/audible',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const SpatialReaderRoute = SpatialReaderRouteImport.update({
  id: '/spatial-reader',
  path: '/spatial-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualLibraryRoute = VirtualLibraryRouteImport.update({
  id: '/virtual-library',
  path: '/virtual-library',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/audible': typeof AudibleRoute
  '/connect': typeof ConnectRoute
  '/graph': typeof GraphRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/reader': typeof ReaderRoute
  '/spatial-reader': typeof SpatialReaderRoute
  '/virtual-library': typeof VirtualLibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/audible': typeof AudibleRoute
  '/connect': typeof ConnectRoute
  '/graph': typeof GraphRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/reader': typeof ReaderRoute
  '/spatial-reader': typeof SpatialReaderRoute
  '/virtual-library': typeof VirtualLibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/audible': typeof AudibleRoute
  '/connect': typeof ConnectRoute
  '/graph': typeof GraphRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/reader': typeof ReaderRoute
  '/spatial-reader': typeof SpatialReaderRoute
  '/virtual-library': typeof VirtualLibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/audible'
    | '/connect'
    | '/graph'
    | '/import'
    | '/library'
    | '/reader'
    | '/spatial-reader'
    | '/virtual-library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/audible'
    | '/connect'
    | '/graph'
    | '/import'
    | '/library'
    | '/reader'
    | '/spatial-reader'
    | '/virtual-library'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/audible'
    | '/connect'
    | '/graph'
    | '/import'
    | '/library'
    | '/reader'
    | '/spatial-reader'
    | '/virtual-library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AudibleRoute: typeof AudibleRoute
  ConnectRoute: typeof ConnectRoute
  GraphRoute: typeof GraphRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRoute
  ReaderRoute: typeof ReaderRoute
  SpatialReaderRoute: typeof SpatialReaderRoute
  VirtualLibraryRoute: typeof VirtualLibraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audible': {
      id: '/audible'
      path: '/audible'
      fullPath: '/audible'
      preLoaderRoute: typeof AudibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spatial-reader': {
      id: '/spatial-reader'
      path: '/spatial-reader'
      fullPath: '/spatial-reader'
      preLoaderRoute: typeof SpatialReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-library': {
      id: '/virtual-library'
      path: '/virtual-library'
      fullPath: '/virtual-library'
      preLoaderRoute: typeof VirtualLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AudibleRoute: AudibleRoute,
  ConnectRoute: ConnectRoute,
  GraphRoute: GraphRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRoute,
  ReaderRoute: ReaderRoute,
  SpatialReaderRoute: SpatialReaderRoute,
  VirtualLibraryRoute: VirtualLibraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
